services:
  - type: web
    name: agroapp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      PYTHON_VERSION: 3.12
